import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import styled from "styled-components"


const Container = styled.div`
  padding: 0 2rem;
  background: #ccc5b9;
`;
const Title = styled.h1`
  font-size: 4rem;
  font-weight: bold;
  color: #403d39;
  margin: 0;
  padding: 1rem 0;
`;
const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
const Hober = styled.a`
    color: #1e84ff;
    text-decoration: none;
    cursor: pointer;
    &:hover ,
    &:focus {
        color: palevioletred;
    }
    &:active {
        color: red;
    }
`;
const Text = styled.p`
    font-size: 1.5rem;
    font-weight: bold;
    color: #403d39;
    margin: 0;
    padding: 1rem 0;
`;
const Grid = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
    max-width: 800px;
`;
const GridItem = styled.div`
    margin: 1rem;
    padding: 1.5rem;
    text-align: left;
    color: inherit;
    text-decoration: none;
    border: 1px solid #eaeaea;
    border-radius: 10px;
    transition: color 0.15s ease, border-color 0.15s ease;
    max-width: 300px;
`;
export default function HOME() {
    return (
        <Container>
            <Head>
                <title>about page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main>
                <Title>
                    Welcome to{' '}
                    <Link href="/">
                        <Hober>LaTexApp</Hober>
                    </Link>
                </Title>


                <Text>
                    Made by{' '}
                    <Hober href="https://nextjs.org/">
                        Next.js
                    </Hober> ,{' '}
                    <Hober href="https://github.com/harunurhan/react-latex-next">
                        react-latex-next
                    </Hober>
                    {' '}and{' '}
                    <Hober href="https://styled-components.com/">
                        styled-components
                    </Hober>
                </Text>

                <Grid>
                    <a href="https://github.com/Nikudanngo/latex-app" className={styles.card}>
                        <h2>Source code &rarr;</h2>
                        <p>The source code of next.js is available on github.</p>
                    </a>

                    <a href="https://firebase.google.com/" className={styles.card}>
                        <h2>Firebase Hosting&rarr;</h2>
                        <p>This site is published by firebase hosting.</p>
                    </a>
                </Grid>
            </Main>
        </Container>
    )

}