import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';


const Test: NextPage = () => {
    var Latex = require('react-latex');
    const Title = styled.h1`
        color: red;
    `;
    return (
        <div className='container'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='main'>
                <Title>
                    <h1 className='title'>
                        Welcome to <a href="https://nextjs.org">Next.js!</a>
                    </h1>
                </Title>
                <h3>
                    <Latex displayMode={true}>$$(3\times 4) \div (5-3)$$</Latex>
                </h3>
            </main>
        </div>
    );
};

export default Test;